"""add language to posts

Revision ID: 852edcd63acb
Revises: 8b162bee1611
Create Date: 2024-12-27 19:13:07.094433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '852edcd63acb'
down_revision = '8b162bee1611'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
